# Generated by Django 5.2.6 on 2025-12-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0064_collectionitineraryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='end_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='start_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
