# Generated by Django 5.2.6 on 2026-01-02 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0065_transportation_end_code_transportation_start_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='primary_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_collections', to='adventures.contentimage'),
        ),
    ]
