# Generated by Django 5.2.8 on 2026-01-05 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0069_location_price_location_price_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionItineraryDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='adventures.collection')),
            ],
            options={
                'verbose_name': 'Collection Itinerary Day',
                'verbose_name_plural': 'Collection Itinerary Days',
                'ordering': ['date'],
                'unique_together': {('collection', 'date')},
            },
        ),
    ]
